from __future__ import annotations

import os
from pathlib import Path
from typing import Protocol
from .jobs import Job, SqliteJobRepository


class JobRepository(Protocol):
    def resume(self, job_id: str, waiting_id: str, answer: str, actor: str, idempotency_key: str) -> Job: ...
    def renew_lease(self, claim: Job, lease_seconds: int) -> None: ...
    def submit(self, job_type: str, payload: dict, idempotency_key: str,
               max_attempts: int = 3) -> tuple[Job, bool]: ...
    def get(self, job_id: str) -> Job | None: ...
    def find_by_trace_id(self, trace_id: str) -> list[Job]: ...
    def claim_next(self, worker_id: str = "worker", lease_seconds: int = 60) -> Job | None: ...
    def finish(self, job_id: str, status: str, result: dict, *, claim: Job) -> Job: ...
    def record_failure(self, job_id: str, code: str, message: str,
                       retryable: bool = True, *, claim: Job, evidence: dict | None = None) -> Job: ...
    def status_counts(self) -> dict[str, int]: ...
    def events(self, job_id: str) -> list[dict]: ...
    def review(self, job_id: str, reviewer: str, decision: str, notes: str = "") -> Job: ...


def job_repository_from_env() -> JobRepository:
    url = os.environ.get("SQL_AGENT_DATABASE_URL")
    if url:
        from .postgres_jobs import PostgresJobRepository
        return PostgresJobRepository(url)
    return SqliteJobRepository(Path(os.environ.get("SQL_AGENT_JOB_DB", "runtime/sql-jobs.db")))
